brew "bat"
brew "fd"
brew "gh"
brew "git-lfs"
brew "lazygit"
brew "libfido2"
brew "llmfit"
brew "mas"
brew "mole"
brew "neovim"
brew "node"
brew "openjdk"
brew "openssh"
brew "ripgrep"
brew "tmux"
brew "yazi"
brew "ykman"

cask "arc"
cask "chatgpt"
cask "clash-verge-rev"
cask "claude"
cask "codex"
cask "cursor"
cask "font-meslo-lg-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "karabiner-elements"
cask "obsidian"
cask "raycast"
cask "slack"
cask "spotify"
cask "tailscale-app"
cask "visual-studio-code"
cask "zotero"

mas "Microsoft Word", id: 462054704
mas "WeChat", id: 836500024
